server:
  port: 8085

spring:
  application:
    name: mypost
  data:
    mongodb:
      host: localhost
      port: 27017
      database: MyPost
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB


rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    groups: mypost.queue
  routing-keys:
    internal-groups: internal.mypost.routing.key

minio:
  endpoint: localhost
  port: 9001
  accessKey: minio
  secretKey: minio123

