server:
  port: 8081

spring:
  application:
    name: groups
  data:
    mongodb:
      host: 192.168.1.57
      port: 27017
      database: GroupChats
  rabbitmq:
    addresses: 192.168.1.57:5672
    username: bor3y
    password: bor3y
    listener:
      simple:
        default-requeue-rejected: false

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    groups: groups.queue
  routing-keys:
    internal-groups: internal.groups.routing.key