server:
  port: 8081

spring:
  application:
    name: groups
  data:
    mongodb:
      host: localhost
      port: 27017
      database: GroupChats
  rabbitmq:
<<<<<<< HEAD
    host: localhost
    username: guest
    password: guest
    port: 5672
=======
    addresses: localhost:5672
    username: bor3y
    password: bor3y
    listener:
      simple:
        default-requeue-rejected: false
>>>>>>> 8904ae04d8d94af4bed8288460147ef413416a14

rabbitmq:
  consumers: 5
  max-consumers: 5
  exchanges:
    internal: internal.exchange
  queues:
    groups: groups.queue
  routing-keys:
    internal-groups: internal.groups.routing.key