server:
  port: 8080
  address: localhost

spring:
  application:
    name: core
  rabbitmq:
    addresses: localhost:5672
    username: bor3y
    password: bor3y
    listener:
      simple:
        default-requeue-rejected: false