version: "3.7"
services:
  groups:
    build: .
    restart: always
    environment:
      RABBITMQ_SERVER: rabbitmq
      MONGO_SERVER: mongo
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - rabbitmq


  mongo:
    container_name: 'mongo'
    image: "mongo:latest"
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/


volumes:
  rabbitmq_data:
  rabbitmq_log:
  data:

networks:
  default:
    external:
      name: test